version: "3.1"

services:
  db:
    image: postgres
    container_name: "telegram-bot-postgres"
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: botadmin
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example

  adminer:
    image: adminer
    container_name: "telegram-bot-adminer"
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
